"""
Interpret and audit the legacy raw-row donation_count XGBoost diagnostic path.

The formal project mainline is now the Gate 7 ensemble generated by
`train_donation_count_xgboost_ensemble.py` and
`analyze_donation_count_xgboost_ensemble.py`.

The trainer owns model fitting and walk-forward splits. This script rebuilds
the same feature matrices, loads each fold model, and writes validation audits:
  - fold-level county-month and county comparison tables
  - root-level compatibility copies for the selected final fold
  - SHAP feature importance for the selected final fold
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))

from plotting_setup import configure_matplotlib_cache

configure_matplotlib_cache()

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap

from train_donation_count_raw_xgboost import (
    CATEGORICAL_FEATURES,
    COUNTY_NAMES,
    CSV_COLS,
    EPSILON,
    NUMERIC_FEATURES,
    OUTDIR,
    TARGET,
    WALK_DIR,
    build_model,
    build_raw_row_frame,
    clean_frame,
    encode_features,
    walk_forward_splits,
    write_json,
)


def json_default(value: Any):
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, (np.ndarray,)):
        return value.tolist()
    raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")


def load_walk_forward_summary() -> dict:
    path = OUTDIR / "walk_forward_summary.json"
    if not path.exists():
        raise FileNotFoundError(f"Missing {path}. Run train_donation_count_raw_xgboost.py first.")
    return json.loads(path.read_text(encoding="utf-8"))


def load_fold_model(fold: str):
    model_path = WALK_DIR / fold / "xgboost_model.json"
    if not model_path.exists():
        raise FileNotFoundError(f"Missing fold model: {model_path}")
    model = build_model()
    model.load_model(str(model_path))
    return model


def prepare_fold_features(fold_spec: dict) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, list[str]]:
    train = clean_frame(fold_spec["train"])
    valid = clean_frame(fold_spec["valid"])
    train_x, valid_x, model_columns, _scalers = encode_features(train, valid)
    return train, valid, train_x, valid_x, model_columns


def write_county_comparison(
    outdir: Path,
    valid: pd.DataFrame,
    valid_x: pd.DataFrame,
    model_columns: list[str],
    model,
    title_suffix: str,
) -> dict:
    preds = model.predict(valid_x[model_columns])
    scored = valid[CSV_COLS + ["county_name"]].copy()
    scored["predicted_donation_count"] = preds
    scored["count_diff"] = scored["predicted_donation_count"] - scored[TARGET]
    scored["abs_count_diff"] = np.abs(scored["count_diff"])
    scored["ape_percent"] = scored["abs_count_diff"] / np.maximum(np.abs(scored[TARGET]), EPSILON) * 100.0
    scored.to_csv(outdir / "validation_predictions.csv", index=False)

    county_month = (
        scored.groupby(["county_label", "county_name", "month"], sort=True)
        .agg(
            actual_donation_count=(TARGET, "first"),
            predicted_donation_count=("predicted_donation_count", "mean"),
            raw_rows=(TARGET, "size"),
            mean_abs_row_error=("abs_count_diff", "mean"),
        )
        .reset_index()
    )
    county_month["year"] = pd.to_datetime(county_month["month"] + "-01").dt.year
    county_month["count_diff"] = county_month["predicted_donation_count"] - county_month["actual_donation_count"]
    county_month["abs_count_diff"] = county_month["count_diff"].abs()
    county_month["pct_diff"] = (
        county_month["count_diff"] / np.maximum(county_month["actual_donation_count"], EPSILON) * 100.0
    )
    county_month["abs_pct_diff"] = county_month["pct_diff"].abs()
    county_month.to_csv(outdir / "county_month_validation_comparison.csv", index=False)

    county = (
        county_month.groupby(["county_label", "county_name"], sort=True)
        .agg(
            actual_donation_count=("actual_donation_count", "sum"),
            predicted_donation_count=("predicted_donation_count", "sum"),
            mean_abs_month_error=("abs_count_diff", "mean"),
            validation_months=("month", "size"),
            raw_rows=("raw_rows", "sum"),
        )
        .reset_index()
    )
    county["count_diff"] = county["predicted_donation_count"] - county["actual_donation_count"]
    county["abs_count_diff"] = county["count_diff"].abs()
    county["pct_diff"] = county["count_diff"] / np.maximum(county["actual_donation_count"], EPSILON) * 100.0
    county["abs_pct_diff"] = county["pct_diff"].abs()
    county = county.sort_values("abs_count_diff", ascending=False).reset_index(drop=True)
    county.to_csv(outdir / "county_validation_comparison.csv", index=False)

    county_year = (
        county_month.groupby(["county_label", "county_name", "year"], sort=True)
        .agg(
            actual_donation_count=("actual_donation_count", "sum"),
            predicted_donation_count=("predicted_donation_count", "sum"),
            validation_months=("month", "size"),
        )
        .reset_index()
    )
    county_year["count_diff"] = county_year["predicted_donation_count"] - county_year["actual_donation_count"]
    county_year["abs_count_diff"] = county_year["count_diff"].abs()
    county_year["pct_diff"] = (
        county_year["count_diff"] / np.maximum(county_year["actual_donation_count"], EPSILON) * 100.0
    )
    county_year["abs_pct_diff"] = county_year["pct_diff"].abs()
    county_year.to_csv(outdir / "county_year_validation_comparison.csv", index=False)

    plt.figure(figsize=(11, 6))
    x = np.arange(len(county))
    width = 0.4
    labels = county["county_label"].map(lambda value: f"C{int(value):02d}")
    plt.bar(x - width / 2, county["actual_donation_count"], width=width, label="Actual")
    plt.bar(x + width / 2, county["predicted_donation_count"], width=width, label="Predicted")
    plt.xticks(x, labels, rotation=35, ha="right")
    plt.ylabel("donation_count sum, county-month deduplicated")
    plt.title(f"County actual vs predicted donation_count - {title_suffix}")
    plt.legend()
    plt.tight_layout()
    plt.savefig(outdir / "county_validation_comparison.png", dpi=130, bbox_inches="tight")
    plt.close()

    summary = {
        "comparison_basis": "county-month deduplicated first, then aggregated to county",
        "largest_abs_count_diff_county": county.iloc[0][
            ["county_name", "abs_count_diff", "pct_diff"]
        ].to_dict(),
        "largest_abs_pct_diff_county": county.sort_values("abs_pct_diff", ascending=False)
        .iloc[0][["county_name", "abs_pct_diff", "count_diff"]]
        .to_dict(),
        "mean_county_abs_pct_diff": float(county["abs_pct_diff"].mean()),
        "median_county_abs_pct_diff": float(county["abs_pct_diff"].median()),
    }
    write_json(outdir / "county_validation_summary.json", summary)
    return summary


def write_shap_outputs(outdir: Path, valid_x: pd.DataFrame, model_columns: list[str], model) -> dict:
    sample_n = min(5000, len(valid_x))
    shap_x = valid_x.sample(n=sample_n, random_state=42).reset_index(drop=True)

    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(shap_x)
    imp = (
        pd.DataFrame({"feature": model_columns, "mean_abs_shap": np.abs(shap_values).mean(axis=0)})
        .sort_values("mean_abs_shap", ascending=False)
        .reset_index(drop=True)
    )
    imp.to_csv(outdir / "shap_importance.csv", index=False)

    plt.figure(figsize=(9, 6))
    top = imp.head(20).iloc[::-1]
    plt.barh(top["feature"], top["mean_abs_shap"], color="tab:green")
    plt.title("donation_count raw-row SHAP importance")
    plt.xlabel("mean |SHAP value|")
    plt.tight_layout()
    plt.savefig(outdir / "shap_importance.png", dpi=130)
    plt.close()

    plt.figure()
    shap.summary_plot(shap_values, shap_x, feature_names=model_columns, show=False, max_display=20)
    plt.tight_layout()
    plt.savefig(outdir / "shap_summary.png", dpi=130, bbox_inches="tight")
    plt.close()

    summary = {
        "target": TARGET,
        "shap_sample_rows": sample_n,
        "top_features": imp.head(15).to_dict(orient="records"),
    }
    write_json(outdir / "shap_summary.json", summary)
    return summary


def copy_root_outputs(selected_fold: str) -> None:
    fold_dir = WALK_DIR / selected_fold
    for name in [
        "validation_predictions.csv",
        "county_month_validation_comparison.csv",
        "county_validation_comparison.csv",
        "county_year_validation_comparison.csv",
        "county_validation_summary.json",
        "county_validation_comparison.png",
        "shap_importance.csv",
        "shap_importance.png",
        "shap_summary.png",
        "shap_summary.json",
    ]:
        src = fold_dir / name
        if src.exists():
            (OUTDIR / name).write_bytes(src.read_bytes())


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    summary = load_walk_forward_summary()
    selected_fold = summary["selected_root_fold"]
    frame = build_raw_row_frame()
    fold_specs = {item["fold"]: item for item in walk_forward_splits(frame)}

    fold_audits = []
    selected_feature_payload = None
    for fold, fold_spec in fold_specs.items():
        outdir = WALK_DIR / fold
        model = load_fold_model(fold)
        _train, valid, _train_x, valid_x, model_columns = prepare_fold_features(fold_spec)
        county_summary = write_county_comparison(outdir, valid, valid_x, model_columns, model, fold)
        shap_summary = None
        if fold == selected_fold:
            shap_summary = write_shap_outputs(outdir, valid_x[model_columns], model_columns, model)
            selected_feature_payload = {
                "model_columns": model_columns,
                "shap_summary": shap_summary,
            }
        fold_audits.append({"fold": fold, **county_summary})

    copy_root_outputs(selected_fold)
    write_json(
        OUTDIR / "audit_summary.json",
        {
            "selected_root_fold": selected_fold,
            "county_names": COUNTY_NAMES,
            "numeric_features": NUMERIC_FEATURES,
            "categorical_features": CATEGORICAL_FEATURES,
            "fold_audits": fold_audits,
            "selected_feature_payload": selected_feature_payload,
        },
    )

    print("Fold audit summary:")
    print(json.dumps(fold_audits, ensure_ascii=False, indent=2, default=json_default))


if __name__ == "__main__":
    main()
